package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int Color = 2;
  public static final int ColorReference = 3;
  public static final int Shape = 4;
  public static final int Square = 5;
  public static final int Triangle = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x74580cf92664bb5L, 0x955558b1421aadc4L);
    builder.put(0x56f824b75a1063e8L, Canvas);
    builder.put(0x56f824b75a1063dcL, Circle);
    builder.put(0x56f824b75a12ff7bL, Color);
    builder.put(0x56f824b75a15616fL, ColorReference);
    builder.put(0x56f824b75a1063d9L, Shape);
    builder.put(0x56f824b75a1063e3L, Square);
    builder.put(0x21accfded7710b32L, Triangle);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
