package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptColorReference = createDescriptorForColorReference();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  /*package*/ final ConceptDescriptor myConceptTriangle = createDescriptorForTriangle();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptColor, myConceptColorReference, myConceptShape, myConceptSquare, myConceptTriangle);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ColorReference:
        return myConceptColorReference;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      case LanguageConceptSwitch.Triangle:
        return myConceptTriangle;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Canvas", 0x74580cf92664bb5L, 0x955558b1421aadc4L, 0x56f824b75a1063e8L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:edc8f71c-3d0f-4ec1-a413-e9639e8a2370(NewLanguage.structure)/6266799251394683880");
    b.version(3);
    b.aggregate("shapes", 0x56f824b75a1063f4L).target(0x74580cf92664bb5L, 0x955558b1421aadc4L, 0x56f824b75a1063d9L).optional(true).ordered(true).multiple(true).origin("6266799251394683892").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Circle", 0x74580cf92664bb5L, 0x955558b1421aadc4L, 0x56f824b75a1063dcL);
    b.class_(false, false, false);
    // extends: NewLanguage.structure.Shape
    b.super_(0x74580cf92664bb5L, 0x955558b1421aadc4L, 0x56f824b75a1063d9L);
    b.origin("r:edc8f71c-3d0f-4ec1-a413-e9639e8a2370(NewLanguage.structure)/6266799251394683868");
    b.version(3);
    b.property("x", 0x56f824b75a1063dfL).type(PrimitiveTypeId.INTEGER).origin("6266799251394683871").done();
    b.property("y", 0x56f824b75a1063e0L).type(PrimitiveTypeId.INTEGER).origin("6266799251394683872").done();
    b.property("radius", 0x56f824b75a1063e1L).type(PrimitiveTypeId.INTEGER).origin("6266799251394683873").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Color", 0x74580cf92664bb5L, 0x955558b1421aadc4L, 0x56f824b75a12ff7bL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:edc8f71c-3d0f-4ec1-a413-e9639e8a2370(NewLanguage.structure)/6266799251394854779");
    b.version(3);
    b.alias("color");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "ColorReference", 0x74580cf92664bb5L, 0x955558b1421aadc4L, 0x56f824b75a15616fL);
    b.class_(false, false, false);
    b.origin("r:edc8f71c-3d0f-4ec1-a413-e9639e8a2370(NewLanguage.structure)/6266799251395010927");
    b.version(3);
    b.associate("target", 0x56f824b75a156170L).target(0x74580cf92664bb5L, 0x955558b1421aadc4L, 0x56f824b75a12ff7bL).optional(false).origin("6266799251395010928").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Shape", 0x74580cf92664bb5L, 0x955558b1421aadc4L, 0x56f824b75a1063d9L);
    b.class_(false, true, false);
    b.origin("r:edc8f71c-3d0f-4ec1-a413-e9639e8a2370(NewLanguage.structure)/6266799251394683865");
    b.version(3);
    b.aggregate("color", 0x56f824b75a15617cL).target(0x74580cf92664bb5L, 0x955558b1421aadc4L, 0x56f824b75a15616fL).optional(false).ordered(true).multiple(false).origin("6266799251395010940").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Square", 0x74580cf92664bb5L, 0x955558b1421aadc4L, 0x56f824b75a1063e3L);
    b.class_(false, false, false);
    // extends: NewLanguage.structure.Shape
    b.super_(0x74580cf92664bb5L, 0x955558b1421aadc4L, 0x56f824b75a1063d9L);
    b.origin("r:edc8f71c-3d0f-4ec1-a413-e9639e8a2370(NewLanguage.structure)/6266799251394683875");
    b.version(3);
    b.property("upperLeftX", 0x56f824b75a1063e4L).type(PrimitiveTypeId.INTEGER).origin("6266799251394683876").done();
    b.property("upperLeftY", 0x56f824b75a1063e5L).type(PrimitiveTypeId.INTEGER).origin("6266799251394683877").done();
    b.property("size", 0x56f824b75a1063e6L).type(PrimitiveTypeId.INTEGER).origin("6266799251394683878").done();
    b.alias("square");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTriangle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguage", "Triangle", 0x74580cf92664bb5L, 0x955558b1421aadc4L, 0x21accfded7710b32L);
    b.class_(false, false, false);
    // extends: NewLanguage.structure.Shape
    b.super_(0x74580cf92664bb5L, 0x955558b1421aadc4L, 0x56f824b75a1063d9L);
    b.origin("r:edc8f71c-3d0f-4ec1-a413-e9639e8a2370(NewLanguage.structure)/2426542855250053938");
    b.version(3);
    b.property("x1", 0x21accfded7710c63L).type(PrimitiveTypeId.INTEGER).origin("2426542855250054243").done();
    b.property("y1", 0x21accfded7710cfaL).type(PrimitiveTypeId.INTEGER).origin("2426542855250054394").done();
    b.property("x2", 0x21accfded7770c1eL).type(PrimitiveTypeId.INTEGER).origin("2426542855250447390").done();
    b.property("y2", 0x21accfded7770c47L).type(PrimitiveTypeId.INTEGER).origin("2426542855250447431").done();
    b.property("x3", 0x21accfded7770c70L).type(PrimitiveTypeId.INTEGER).origin("2426542855250447472").done();
    b.property("y3", 0x21accfded7770c8fL).type(PrimitiveTypeId.INTEGER).origin("2426542855250447503").done();
    b.alias("triangle");
    return b.create();
  }
}
